version: "3.8"
services:
  users:
    build: ./backend
    command:
      - "-mongoURI"
      - "mongodb://mongodb:27017/"
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host

  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodata:/data/db
